### ISSUE TITLE
Adding Persian Spellchecker to LanguageTool

### ISSUE THREAD

**Issue by armingrudd** [b00f/lilak#44]
There is a great and open source tool for checking spell and grammar named LanguageTool which is also used in other tools or platforms like [KNIME Spellchecker nodes](https://nodepit.com/node/de.philippkatz.knime.spellchecker.simple.SpellCheckerNodeFactory).
They have already added Persian language to the tool but it cannot check for spelling in Persian.
I asked them about this [here](https://forum.languagetool.org/t/the-tool-does-not-recognize-so-many-spelling-mistakes-in-persian-language/3925) and they suggested to add Hunspell-based Persian dictionary.
Would you please cooperate on this?

**Comment by b00f** [comment]
Sure. I will be glad to help Persian community for using Lilak to improve writings. But as I understood they need just the hunspell dictionary which you can download it [here](https://sourceforge.net/projects/lilak/files/Version%203.0/fa_IR.zip/download)

Let me know what else you might need.

**Comment by armingrudd** [comment]
Honestly I don't have any expertise in this area.
Would you help me to maintain Persian language in LanguageTool?
I checked the documentations and could add more than 350 rules for Persian in a few hours but they suggested to use a Hunspell-based dictionary for that.
As you are an expert in this area I think you can handle it easily or at least guide me through this.
Thanks.

**Comment by b00f** [comment]
I do believe you can easily manage and maintain it. Let me explain a bit.
[Hunspell](http://hunspell.github.io/) is a free and open source spell checker which is widely using by so many projects in the world. Good news is that it is supporting Unicode (UTF-8) encoding which let languages other than English to use it for spell-checking. 
So far we have the right software, but this software to work well needs a dictionary per language. **Lilak** actually is a Persian dictionary for Hunspell library. So in your case LanguageTool needs only a dictionary to support Persian language which is here. You can download it and place it among the other dictionaries. 
In case you need word frequencies I have this project as well:
https://github.com/tihu-nlp/trigram_word_frequency
