### ISSUE TITLE
how to use this in libre office

### ISSUE THREAD

**Issue by vbeh** [b00f/lilak#45]
hi 
i have Hunspell spell checker on Libre office is there any simple way to add this to Hunspell ?
-thank you :+1:

**Comment by b00f** [comment]
Take a look at [here](https://github.com/LibreOffice/dictionaries)
You can find the dic and aff files [here](https://github.com/b00f/lilak/releases/tag/v3.2)

**Comment by vbeh** [comment]
for any other linux user: put the aff and dic files in this directory: 
/usr/share/hunspell
its working :)
thank you :)

**Comment by b00f** [comment]
@vbeh Can you add Lilak dictionary into Libre Office, here:  https://github.com/LibreOffice/dictionaries

It is so pity that Persian is not listed there. Somebody should do it.

**Comment by reza1615** [comment]
I opened a ticket. [here](https://github.com/LibreOffice/dictionaries/issues/22)
