### ISSUE TITLE
فرمت استاندارد برای نسخهٔ ۳.۲ لیلک

### ISSUE THREAD

**Issue by neesti** [b00f/lilak#50]
<div dir=rtl>
سلام. 
شما بهتر از من می‌دانید که افزونه‌های استاندارد لیبره‌آفیس در فرمت OXT منتشر می‌شوند. 
نسخهٔ ۳.۲ افزونه در چنین قالبی منتشر نشده و کاربران عادی نمی‌توانند به‌سادگی نصبش کنند. 
ممنون می‌شوم این نقص را برطرف کنید.

**Comment by b00f** [comment]
Thanks for using Lilak. You can download oxt extension file [here](https://github.com/b00f/lilak/releases/tag/v3.3) 

Could you please add this extension to the official  website? https://extensions.libreoffice.org/
