### ISSUE TITLE
Adding lilak to LibreOffice

### ISSUE THREAD

**Issue by b00f** [b00f/lilak#51]
Currently LibreOffice has no dictionary for Persian language. 
All the dictionaries for Libre Office are listed [here](https://github.com/LibreOffice/dictionaries)

We need to add latest release to this repo.

**Comment by afshin-ir** [comment]
Now, there is Persian dictionary:

https://github.com/LibreOffice/dictionaries/tree/master/fa_IR

**Comment by b00f** [comment]
Good job @neesti
