### ISSUE TITLE
ترکیب با دیکشنری انگلیسی

### ISSUE THREAD

**Issue by nadrad** [b00f/lilak#55]
ممنون از زحمتی که کشیدین. 
فکر خوبی هست که دیکشنری انگلیسی هم داخلش اضافه بشه یا نسخه دومی ازش وجود داشته باشه که ترکیبی از دیکشنری انگلیسی و فارسی باشه؟
حداقل برای من دو امتیاز داره: یکی این‌که تو متن فارسی‌ای که عبارت‌های انگلیسی وجود داشته باشه هم انگلیسی‌ها اشتباه به حساب نمیان که صفحه رو شلوغ کنن و هم به تشخیص اشتباه‌های تایپی تو عبارت‌های انگلیسی کمک می‌کنه و یکی دیگه این‌که تو فایرفاکس که زبان رو به طور خودکار بر اساس محتوا حدس نمی‌زنه و انتخاب نمی‌کنه می‌تونیم دیکشنری رو دایما روی فارسی بذاریم و ازش هم برای نوشتن فارسی استفاده کنیم و هم انگلیسی.

من خواستم برای آزمایش خودم این کار رو بکنم، ولی متاسفانه تداخل‌هایی پیش میاد که برای حل کردنش باید اطلاعات کاملی در مورد این نوع دیکشنری داشت.

**Comment by nadrad** [comment]
این رو هم یادم رفت بگم که تو جستجوهایی که کردم متوجه شدم که برای بعضی زبان‌های دیگه، مثل روسی، چنین ترکیبی وجود داره. وقتی الفبای زبان لاتین نباشه فرصت خیلی خوبیه برای این کار، چون کلمه‌های دو زبان با هم اشتباه گرفته نمی‌شن.

**Comment by b00f** [comment]
Thanks for your suggestion. We are not going to do that. Because [Hunspell](https://hunspell.github.io/) is multi language. What you need is just using Hunspell with different dictionaries.
